name: Build

on: 
  pull_request:

jobs:
  dev-tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      previous_tag: ${{ steps.tag_version.outputs.previous_tag }}
    steps:
      - name: Create tmp dev-tag for docker image
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.CI_BOT_TOKEN }}
          release_branches: master,main
          # Generate specific tag for pre-release
          pre_release_branches: "^(?!main$|master$).*$"
          # Dont tag if the commit is not a patch, minor or major
          default_bump: false
          # Set tag as x.x.x
          tag_prefix: "dev-"

      - name: Delete tmp dev tag
        uses: dev-drprasad/delete-tag-and-release@v1.0 
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          github_token: ${{ secrets.CI_BOT_TOKEN }}  
          delete_release: false

  build-dev-docker-image:
    runs-on: ubuntu-latest
    needs: [dev-tag]
    # Run only if there is tag generated from previous jobs
    if: ${{ needs.dev-tag.outputs.new_tag }}
    env:
      GHCR_REGISTRY: ghcr.io
      GHCR_REGISTRY_REPO: ${{ secrets.GHCR_REPO }}
      DOCKERFILE_PATH: Dockerfile
    steps:   
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get repository name
        id: get_repo_name
        run: |
          result=$(echo "$GITHUB_REPOSITORY" | awk -F'/' '{print $2}')
          echo "repo_name=$result" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ secrets.CI_BOT_USERNAME }}
          password: ${{ secrets.CI_BOT_TOKEN }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REGISTRY_REPO }}/${{ steps.get_repo_name.outputs.repo_name }}:${{ needs.dev-tag.outputs.new_tag }}
    